import jsPDF from 'jspdf'
import 'jspdf-autotable'

export function generatePDF(patientName, resultData) {
  const doc = new jsPDF()

  // Colors
  const primaryColor = [61, 123, 245]
  const darkTextColor = [30, 30, 30]

  // Header Title
  doc.setFillColor(...primaryColor)
  doc.rect(0, 0, 210, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('AURALYSIS', 15, 25, { charSpace: 2 })

  // Subtitle
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('AI-Powered Medical Image Analysis', 15, 32)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 160, 25)

  // Disease Info
  doc.setTextColor(...darkTextColor)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Clinical Diagnosis Report', 15, 55)

  // Top info box
  doc.setDrawColor(200, 200, 200)
  doc.setFillColor(245, 248, 255)
  doc.roundedRect(15, 60, 180, 25, 3, 3, 'FD')

  doc.setFontSize(11)
  doc.text(`Patient: ${patientName}`, 20, 68)
  
  const dis = resultData.disease || resultData.prediction || 'Unknown'
  const conf = ((resultData.confidence || 0) * 100).toFixed(1)
  doc.text(`Diagnosis: ${dis}`, 20, 78)
  doc.text(`Confidence: ${conf}%`, 130, 78)

  // Use either nested medical_report structure or flat
  let medicalData = resultData
  if (resultData.medical_report) {
    if (typeof resultData.medical_report === 'string') {
        try { medicalData = JSON.parse(resultData.medical_report) } catch(e){}
    } else {
        medicalData = resultData.medical_report
    }
  } else if (typeof resultData.report_summary === 'string') {
      try { medicalData = JSON.parse(resultData.report_summary) } catch(e){}
  }

  const sections = []
  
  const addSec = (title, content) => {
    if(!content || content.length === 0) return
    let text = ''
    if (Array.isArray(content)) {
      text = content.map((c, i) => `${i + 1}. ${c}`).join('\n')
    } else {
      text = String(content)
    }
    sections.push({ title, content: text })
  }

  addSec('Medical Explanation', medicalData.medical_explanation)
  addSec('Possible Symptoms', medicalData.possible_symptoms)
  addSec('Recommended Next Steps', medicalData.recommended_next_steps)
  addSec('Severity Level', medicalData.severity_level)
  addSec('Specialist to Consult', medicalData.specialist_to_consult)
  addSec('Emergency Signs', medicalData.emergency_signs_to_watch)

  if (sections.length === 0) {
      if (typeof resultData.report_summary === 'string') {
           addSec('Summary', resultData.report_summary)
      } else {
           addSec('Summary', 'No detailed report available.')
      }
  }

  // Draw sections
  let currentY = 95
  
  doc.autoTable({
    startY: currentY,
    head: [],
    body: sections.map(s => [s.title, s.content]),
    theme: 'grid',
    styles: { 
      fontSize: 10,
      cellPadding: 6,
      lineColor: [220, 220, 220],
      lineWidth: 0.1
    },
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [250, 250, 250], cellWidth: 50, textColor: [50, 50, 50] },
      1: { cellWidth: 130, textColor: [30, 30, 30] }
    },
    margin: { left: 15 }
  })

  currentY = doc.lastAutoTable.finalY + 20

  // Disclaimer
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.setFont('helvetica', 'italic')
  
  const discText = doc.splitTextToSize(
    'Disclaimer: This analysis was generated by Artificial Intelligence. It is intended for informational and educational purposes only and does not constitute professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
    180
  )
  
  // Ensure disclaimer fits, if not, add page
  if (currentY + (discText.length * 5) > 280) {
      doc.addPage()
      currentY = 20
  }
  
  doc.text(discText, 15, currentY)

  doc.save(`Auralysis_Report_${new Date().getTime()}.pdf`)
}
