name: auralysis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 📌 Required to pick image from gallery/camera
  image_picker: ^1.0.7

  # 📌 Required to send the image to your API server
  http: ^1.1.0
  permission_handler: ^12.0.1
  audioplayers: ^6.1.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/auralysis.png
